[tool.poetry]
name = "thea-web"
version = "0.1.0"
description = "Thea Botanicals AI Agent"
authors = ["Dan Spencer"]

[tool.poetry.dependencies]
python = "^3.11"
anthropic = "*"
flask = "*"
flask-cors = "*"
requests = "*"
gunicorn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"